### ISSUE TITLE
Error while using pylmeasure : Permission denied to .swc file

### ISSUE THREAD

**Issue by sebgra** [JustasB/pylmeasure#1]
Hello !

First of all, thanks for this amazing wrapper. I'm trying to use it to get features from swc files. I have tried to reproduce the example given through the notebook. Unfortunatly I wasn't able to run the notebook (and the same python script) due to : 

> PermissionError: [Errno 13] Permission denied

I have already tried to modify permissions with chmod 777 for all files in the folder but it didn't change anything. I have installed pylmeasure with the command given in the presentation into a conda env. 

Any help ?

Thanks in advance

**Comment by JustasB** [comment]
Hi @sebgra, It looks like a permissions issue. Are you able to run the basic example from the repository root (https://github.com/JustasB/pylmeasure) without the error?

```
from pylmeasure import *
LMOutput = getOneMeasure('Surface', 'path/to/cell.swc')
print("Surface area:",  LMOutput["TotalSum"])
```

If the above works, we can then see if there is something specific to the notebook that causes the problem.

**Comment by sebgra** [comment]
Hello @JustasB,

I have tried what you have mentioned, I have downloaded your tutorial notebook (and associated files), and I got the same problem 

> ~/miniconda3/envs/Optimisation/lib/python3.5/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1287                             else:
   1288                                 err_msg += ': ' + repr(orig_executable)
-> 1289                     raise child_exception_type(errno_num, err_msg)
   1290                 raise child_exception_type(err_msg)
   1291 

 >PermissionError: [Errno 13] Permission denied


I have also tried the following code : 

```
from pylmeasure import *

LMOutput = getOneMeasure('Surface', '/Users/Sebastien/Documents/IMA/PRAT/PRAT/tests/testFiles/HB130313-4NS.swc')
print("Surface area:",  LMOutput["TotalSum"])
```
And the same error occured, despite a 777 mode for all the files and the subfolders files.

Any idea on how to give permission ?

Thanks in advance

**Comment by JustasB** [comment]
Hmm it might be when it's creating temporary files.

Can you create a folder in your user directory e.g. "~/pylmtest", then place a test SWC file in that folder, then start python from that folder, and run the three example lines?

When the 'getOneMeasure' line runs, it will attempt to create a new folder in the working directory e.g. "~/pylmtest/tmp". It might not have write access to the working dir to create the folder. Can you try the above and see if you still get the error?

**Comment by sebgra** [comment]
Got the same problem, permission denied. To be more precise I have created a folder like "~/pylmtest", then copied the script and the swc file, activate the conda env and run the script. 

I have verified, all users have the right to read, copy and execute (777 mode) all files and folders.

I use to work with conda envs, and the miniconda3 python installation, maybe this lead to the permission error ?

Thanks

**Comment by JustasB** [comment]
I don't believe it's conda. I just tried it on conda with python 2 and 3 and it worked without the problem. I also just tried it on a clean Ubuntu machine and it worked fine too.

At this point, I'm out of guesses on what is causing the problem. It's probably one of the lines in the [LMIOFunction](https://github.com/JustasB/pylmeasure/blob/master/pylmeasure/__init__.py#L452). 

You could add some `print` statements to the function and any sub-calls to narrow down which specific line is causing the error.

You can find the path of the py file to modify  with:

```
import pylmeasure
pylmeasure
```

`LMIOFunction` is on line 452: https://github.com/JustasB/pylmeasure/blob/master/pylmeasure/__init__.py#L452

**Comment by sebgra** [comment]
Hello,

I've tried what you have mentionned yesterday, it didn't change anything, but I have found a solution : I've given all permission to the miniconda3/ repertory. It seems to have change something because now there still an error but not the same : 

`LMOutput = getOneMeasure('Surface','/Users/Sebastien/Documents/IMA/PRAT/PRAT/tests/testFiles/HB130313-4NS.swc')
`
Returns : 

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/Sebastien/miniconda3/envs/PRAT/lib/python3.7/site-packages/pylmeasure/__init__.py", line 512, in getOneMeasure
>     result = getMeasure([measure], [swcFile], PCA=PCA, specificity=specificity)
>   File "/Users/Sebastien/miniconda3/envs/PRAT/lib/python3.7/site-packages/pylmeasure/__init__.py", line 499, in getMeasure
>     return LMIOFunction('getMeasure', swcFileNames, measureNames, PCA=PCA, specificity=specificity)
>   File "/Users/Sebastien/miniconda3/envs/PRAT/lib/python3.7/site-packages/pylmeasure/__init__.py", line 471, in LMIOFunction
>     lmRun.runLM(LMInputFName, LMOutputFName, LMLogFName)
>   File "/Users/Sebastien/miniconda3/envs/PRAT/lib/python3.7/site-packages/pylmeasure/__init__.py", line 289, in runLM
>     stdout=LMLogFle, stderr=LMLogFle)
>   File "/Users/Sebastien/miniconda3/envs/PRAT/lib/python3.7/subprocess.py", line 323, in call
>     with Popen(*popenargs, **kwargs) as p:
>   File "/Users/Sebastien/miniconda3/envs/PRAT/lib/python3.7/subprocess.py", line 775, in __init__
>     restore_signals, start_new_session)
>   File "/Users/Sebastien/miniconda3/envs/PRAT/lib/python3.7/subprocess.py", line 1522, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> OSError: [Errno 8] Exec format error: '/Users/Sebastien/miniconda3/envs/PRAT/lib/python3.7/site-packages/pylmeasure/LMMac/lmeasure'

Any idea ?

**EDIT :** 

I was working on mac so far, I tried it on Linux and it works, without Permission error neither Exec format Error, I will use Linux, but I'd like to use it on mac. Finally I got a solution to continue my work. 

Thanks in advance

**Comment by JustasB** [comment]
I see. It looks like a problem specific to mac os. The error indicates there is something wrong with the mac binary of lmeasure. I'm traveling and don't have my mac handy, but I suspect that if you replaced the binary with the latest version, the code would continue without that error.

You can download the latest mac lmeasure version from: http://cng.gmu.edu:8080/Lm/release/mac/Lm.htm

Then extract and overwrite `Lm.jar` and `lmeasure` from the zip file into this folder:
`/Users/Sebastien/miniconda3/envs/PRAT/lib/python3.7/site-packages/pylmeasure/LMMac/` 

I'll need to look into why the extra permissions need to be given under macos but not linux.

**Comment by JustasB** [comment]
I replaced the mac lmeasure binaries and added the extra permissions install step for mac os. It passed all the unit tests on mac os afterward. I believe this should address the issue you've been having.

You can get the latest version with:

```
pip uninstall pylmeasure
pip install pylmeasure
```

Let me know if this works on your mac now.

**Comment by sebgra** [comment]
Hello,

It works fine ! After uninstalling and installing the new version I, however had to give all permission to the /miniconda3/ directory, but now it works !  

Thanks a lot for taking the time to fix the problem.

Sébastien

**Comment by JustasB** [comment]
I'm glad that it's working now :)

I'll keep looking into the permissions issue. It seems to be osx related, because there is no need to add the extra permissions on Ubuntu or Windows.

Thanks for reporting the issue and helping to debug it.

**Comment by JustasB** [comment]
@rgerkin pyLMeasure should now work on Mac OS without issues
